apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-raincoat-coatrack
  annotations:
    # use the shared ingress-nginx
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/issuer: "letsencrypt-prod"
    # type of authentication
#    nginx.ingress.kubernetes.io/auth-type: basic
    # name of the secret that contains the user/password definitions
#    nginx.ingress.kubernetes.io/auth-secret: basic-auth-dev
    # message to display with an appropriate context why the authentication is required
#    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required'
    # Allow some IPs through
    nginx.ingress.kubernetes.io/whitelist-source-range: "127.0.0.1/0"
  namespace: coatrack
spec:
  tls:
  - hosts:
    - raincoat.prod.coatrack.eu
    secretName: coatrack-raincoat-tls
  rules:
  - host: raincoat.prod.coatrack.eu
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: coatrack-raincoat
            port:
              number: 80
